name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['python3.6', 'python3.7', 'python3.8', 'python3.9', 'python3.10']

    env:
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      PWD_TOKEN: ${{ secrets.PWD_TOKEN }}
      TESTS_FILE: 'tests/general_tests.py'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
