name: Tests

on:
  - workflow_dispatch

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    env:
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      PWD_TOKEN: ${{ secrets.PWD_TOKEN }}
      TESTS_FILE: 'tests/general_tests.py'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Test with pytest
        run: pytest -v tests/test_general.py
